# Generated by Django 5.2.3 on 2025-10-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0003_funcionario_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='chefe',
            field=models.OneToOneField(blank=True, help_text='Funcionário responsável por este setor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setor_chefiado', to='funcionarios.funcionario', verbose_name='Chefe do Setor'),
        ),
    ]
