# Generated by Django 5.2.3 on 2025-10-02 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setor_chefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFixoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher se o impacto for Valor Fixo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher se o impacto for Percentual da Base', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentual')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixar em branco para lançamento permanente', null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('provento_desconto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proventodesconto', verbose_name='Provento/Desconto')),
            ],
            options={
                'verbose_name': 'Lançamento Fixo Geral',
                'verbose_name_plural': 'Lançamentos Fixos Gerais',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
