# Generated by Django 5.2.3 on 2025-10-01 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salário Base')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('F', 'Férias'), ('L', 'Licença')], default='A', max_length=1, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='core.funcao', verbose_name='Função')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='core.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('periodo_aquisitivo_inicio', models.DateField(verbose_name='Início do Período Aquisitivo')),
                ('periodo_aquisitivo_fim', models.DateField(verbose_name='Fim do Período Aquisitivo')),
                ('data_inicio_gozo', models.DateField(verbose_name='Início do Gozo')),
                ('data_fim_gozo', models.DateField(verbose_name='Fim do Gozo')),
                ('dias_corridos', models.IntegerField(default=30, verbose_name='Dias Corridos')),
                ('status', models.CharField(choices=[('PR', 'Programada'), ('EG', 'Em Gozo'), ('CO', 'Concluída'), ('CA', 'Cancelada')], default='PR', max_length=2, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'ordering': ['-data_inicio_gozo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carga Horária (horas/semana)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipocontrato', verbose_name='Tipo de Contrato')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_adiantamento', models.DateField(verbose_name='Data do Adiantamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('D', 'Descontado'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Adiantamento',
                'verbose_name_plural': 'Adiantamentos',
                'ordering': ['-data_adiantamento'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher se o impacto for Valor Fixo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher se o impacto for Percentual da Base', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentual')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixar em branco para lançamento permanente', null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_fixos', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('provento_desconto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proventodesconto', verbose_name='Provento/Desconto')),
            ],
            options={
                'verbose_name': 'Lançamento Fixo',
                'verbose_name_plural': 'Lançamentos Fixos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
