# Generated by Django 5.2.3 on 2025-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='CPF, E-mail, Telefone ou Chave Aleatória', max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/', verbose_name='Foto'),
        ),
    ]
