# Generated by Django 5.2.3 on 2025-10-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_chave_pix_funcionario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='superior',
            field=models.ForeignKey(blank=True, help_text='Funcionário responsável direto por este colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='funcionarios.funcionario', verbose_name='Superior/Responsável'),
        ),
    ]
