# Generated by Django 5.2.3 on 2025-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='participa_folha',
            field=models.BooleanField(default=True, help_text='Desmarque para funcionários que não devem aparecer na folha (ex: sócios, consultores externos)', verbose_name='Participa da Folha de Pagamento'),
        ),
    ]
