# Generated by Django 4.2.7 on 2026-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_adiciona_participa_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='adiantamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
