# Generated by Django 4.2.7 on 2026-08-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lancamentofixogeral'),
        ('funcionarios', '0005_adiantamento_data_pagamento_adiantamento_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.tipocontrato', verbose_name='Tipo de Contrato'),
        ),
    ]
