# Generated by Django 5.2.3 on 2025-10-01 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mês')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('R', 'Rascunho'), ('F', 'Fechada'), ('P', 'Paga'), ('C', 'Cancelada')], default='R', max_length=1, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contratos_ativos', models.ManyToManyField(blank=True, related_name='folhas', to='funcionarios.contrato', verbose_name='Contratos Ativos')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ItemFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor_lancado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Lançado')),
                ('base_calculo', models.DecimalField(blank=True, decimal_places=2, help_text='Base utilizada para cálculo percentual', max_digits=10, null=True, verbose_name='Base de Cálculo')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='folha.folhapagamento', verbose_name='Folha de Pagamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_folha', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('provento_desconto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proventodesconto', verbose_name='Provento/Desconto')),
            ],
            options={
                'verbose_name': 'Item da Folha',
                'verbose_name_plural': 'Itens da Folha',
                'ordering': ['folha_pagamento', 'funcionario', 'provento_desconto'],
            },
        ),
        migrations.CreateModel(
            name='ResumoFolhaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Proventos')),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Descontos')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Líquido')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos', to='folha.folhapagamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_folha', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Resumo da Folha por Funcionário',
                'verbose_name_plural': 'Resumos da Folha por Funcionário',
                'unique_together': {('folha_pagamento', 'funcionario')},
            },
        ),
    ]
