# Generated by Django 5.0.1 on 2025-10-31 01:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def criar_eventos_padrao(apps, schema_editor):
    """
    Cria um evento padrão para cada folha de pagamento existente
    e associa todos os itens existentes a esse evento
    """
    FolhaPagamento = apps.get_model('folha', 'FolhaPagamento')
    EventoPagamento = apps.get_model('folha', 'EventoPagamento')
    ItemFolha = apps.get_model('folha', 'ItemFolha')
    
    for folha in FolhaPagamento.objects.all():
        # Cria um evento padrão "Pagamento Final" para cada folha existente
        # Usa o último dia do mês como data do evento
        import calendar
        ultimo_dia = calendar.monthrange(folha.ano, folha.mes)[1]
        
        from datetime import date
        data_evento = date(folha.ano, folha.mes, ultimo_dia)
        
        evento = EventoPagamento.objects.create(
            folha_pagamento=folha,
            tipo_evento='PF',
            descricao=f'Pagamento Final {folha.mes:02d}/{folha.ano}',
            data_evento=data_evento,
            status=folha.status,  # Mantém o mesmo status da folha
            valor_total=Decimal('0.00')
        )
        
        # Associa todos os itens existentes desta folha ao novo evento
        ItemFolha.objects.filter(folha_pagamento=folha).update(
            evento_pagamento=evento
        )
        
        # Recalcula o valor total do evento
        itens = ItemFolha.objects.filter(evento_pagamento=evento)
        total_proventos = sum(
            item.valor_lancado for item in itens 
            if item.provento_desconto.tipo == 'P'
        )
        total_descontos = sum(
            item.valor_lancado for item in itens 
            if item.provento_desconto.tipo == 'D'
        )
        evento.valor_total = total_proventos - total_descontos
        evento.save()


def reverter_eventos(apps, schema_editor):
    """
    Remove a associação dos itens com eventos (para rollback)
    """
    # Não é necessário fazer nada, pois a remoção do campo evento_pagamento
    # será tratada pela própria migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0001_initial'),
    ]

    operations = [
        # 1. Altera as opções do modelo ItemFolha (preparação)
        migrations.AlterModelOptions(
            name='itemfolha',
            options={
                'ordering': ['folha_pagamento', 'funcionario', 'provento_desconto'],
                'verbose_name': 'Item da Folha',
                'verbose_name_plural': 'Itens da Folha'
            },
        ),
        
        # 2. Altera o campo folha_pagamento (adiciona help_text)
        migrations.AlterField(
            model_name='itemfolha',
            name='folha_pagamento',
            field=models.ForeignKey(
                help_text='Referência à competência (mantida para compatibilidade)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='itens',
                to='folha.folhapagamento',
                verbose_name='Folha de Pagamento'
            ),
        ),
        
        # 3. Cria o modelo EventoPagamento
        migrations.CreateModel(
            name='EventoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_evento', models.CharField(
                    choices=[
                        ('AD', 'Adiantamento Quinzenal'),
                        ('PF', 'Pagamento Final'),
                        ('13', '13º Salário'),
                        ('FE', 'Férias'),
                        ('RE', 'Rescisão'),
                        ('OU', 'Outros')
                    ],
                    default='PF',
                    max_length=2,
                    verbose_name='Tipo de Evento'
                )),
                ('descricao', models.CharField(
                    help_text='Ex: Adiantamento Quinzenal 15/01, Pagamento Final 30/01',
                    max_length=200,
                    verbose_name='Descrição'
                )),
                ('data_evento', models.DateField(
                    help_text='Data prevista ou realizada do pagamento',
                    verbose_name='Data do Evento'
                )),
                ('data_pagamento', models.DateField(
                    blank=True,
                    help_text='Data em que o pagamento foi efetivamente realizado',
                    null=True,
                    verbose_name='Data do Pagamento'
                )),
                ('status', models.CharField(
                    choices=[
                        ('R', 'Rascunho'),
                        ('F', 'Fechado'),
                        ('P', 'Pago'),
                        ('C', 'Cancelado')
                    ],
                    default='R',
                    max_length=1,
                    verbose_name='Status'
                )),
                ('valor_total', models.DecimalField(
                    decimal_places=2,
                    default=Decimal('0.00'),
                    help_text='Calculado automaticamente a partir dos itens',
                    max_digits=12,
                    verbose_name='Valor Total do Evento'
                )),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('folha_pagamento', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='eventos',
                    to='folha.folhapagamento',
                    verbose_name='Folha de Pagamento'
                )),
            ],
            options={
                'verbose_name': 'Evento de Pagamento',
                'verbose_name_plural': 'Eventos de Pagamento',
                'ordering': ['folha_pagamento', 'data_evento'],
                'unique_together': {('folha_pagamento', 'descricao')},
            },
        ),
        
        # 4. Adiciona o campo evento_pagamento (nullable temporariamente)
        migrations.AddField(
            model_name='itemfolha',
            name='evento_pagamento',
            field=models.ForeignKey(
                null=True,  # Temporariamente nullable
                on_delete=django.db.models.deletion.CASCADE,
                related_name='itens',
                to='folha.eventopagamento',
                verbose_name='Evento de Pagamento'
            ),
        ),
        
        # 5. Executa a função de migração de dados
        migrations.RunPython(criar_eventos_padrao, reverter_eventos),
        
        # 6. Remove o null do campo evento_pagamento
        migrations.AlterField(
            model_name='itemfolha',
            name='evento_pagamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='itens',
                to='folha.eventopagamento',
                verbose_name='Evento de Pagamento'
            ),
        ),
        
        # 7. Atualiza as opções de ordenação do ItemFolha
        migrations.AlterModelOptions(
            name='itemfolha',
            options={
                'ordering': ['evento_pagamento', 'funcionario', 'provento_desconto'],
                'verbose_name': 'Item da Folha',
                'verbose_name_plural': 'Itens da Folha'
            },
        ),
    ]
