# Generated by Django 5.0.1 on 2025-12-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0002_adiciona_eventos_pagamento'),
        ('funcionarios', '0004_adiciona_participa_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfolha',
            name='adiantamento_origem',
            field=models.ForeignKey(blank=True, help_text='Referência ao adiantamento original (quando aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_desconto', to='funcionarios.adiantamento', verbose_name='Adiantamento Origem'),
        ),
    ]
