# Generated by Django 5.0.1 on 2026-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0003_adiciona_rastreabilidade_adiantamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumofolhafuncionario',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='resumofolhafuncionario',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
