# Generated by Django 4.2.7 on 2026-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha', '0004_pagamento_individual_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfolha',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='itemfolha',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
